import { Inter } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import { auth } from "@/auth";
import { FoodProvider } from "@/context/FoodContext";
import { IngredientsProvider } from "@/context/IngredientsContext";
const inter = Inter({ subsets: ["latin"] });

import { Toaster } from "@/components/ui/toaster";
import { ThemeProvider } from "@/components/ThemeProvider";

export const metadata = {
  title: "My Daily Macros",
  description: "Generated by create next app",
};

export const viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
};

export default async function RootLayout({ children }) {
  const session = await auth();

  return (
    <SessionProvider session={session}>
      <FoodProvider>
        <IngredientsProvider>
          <html lang="en" suppressHydrationWarning>
            <body className={inter.className}>
              <ThemeProvider
                attribute="class"
                defaultTheme="system"
                enableSystem
                disableTransitionOnChange
              >
                {children}
                <Toaster />
              </ThemeProvider>
            </body>
          </html>
        </IngredientsProvider>
      </FoodProvider>
    </SessionProvider>
  );
}
