name: Docker build and push

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io/${{ github.repository_owner }}
  IMAGE_NAME: macros-calculator

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Build docker image
        run: docker build . --file Dockerfile --tag $REGISTRY/$IMAGE_NAME:latest
      - name: Log in to the Container registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push image
        run: |
          IMAGE_ID=$REGISTRY/$IMAGE_NAME
          docker push $IMAGE_ID:latest
